name: scyllavault
main: me.scylla.vaults.Main
version: 1.0
description: Scylla vaults

commands:
  sv:
    description: vault command

permissions:
  sv.admin:
    description: Allows access to view and edit others vaults